spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    url: jdbc:mysql://127.0.0.1/pr?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
logging:
  level:
    layui.demo.layuidemo.mapper.UserMapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
